// <auto-generated />
using LaxWebApplication.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace LaxWebApplication.Migrations.GameEvents
{
    [DbContext(typeof(GameEventsContext))]
    [Migration("20180329193537_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LaxWebApplication.Models.GameEvents", b =>
                {
                    b.Property<int>("EventTime")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ActingTeamMemberNumber");

                    b.Property<int>("AssistingTeamMember");

                    b.Property<string>("EventType");

                    b.Property<int>("HomeScore");

                    b.Property<int>("PenaltyTime");

                    b.Property<string>("PenaltyType");

                    b.Property<string>("Team")
                        .IsRequired();

                    b.Property<int>("VisitorScore");

                    b.HasKey("EventTime");

                    b.ToTable("GameEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
